// Autogenerated file 
let data = [ 

{
    "type": "Feature",
    "properties": {
        "name": "Häckerei",
        "amenity": "haeckerei",
        "description": "Wir liefern nix, wir holen nur.",
        "address": "Am Ende der Welt 12",
        "phone": "0911 543 21",
        "mail": "do-not-reply@example.com",
        "webseite": "example.com"
    },
    "geometry": {
        "type": "Point",
        "coordinates": [
            11.280840,
            49.549080
        ]
    }
}

,
{
    "type": "Feature",
    "properties": {
        "name": "Onkel Waus Hackwaren",
        "amenity": "haeckerei",
        "description": "Wir liefern alle unsere Hackwaren auch in ganz Nürnberg. Rufen sie uns einfach an.",
        "address": "Peuntgasse 5, 90402 Nürnberg",
        "phone": "0911 123 456",
        "mail": "info@k4cg.org",
        "webseite": "https://k4cg.org"
    },
    "geometry": {
        "type": "Point",
        "coordinates": [
            11.080840,
            49.449080
        ]
    }
},{}]; 
